---
# Account name of remote user. Ansible will use this user account to ssh into
# the managed machines. 
ansible_ssh_user: centos
# Account SSH pubkey of remote user. Ansible will use this key to
ansible_ssh_pubkey: "{{ lookup('file','~/.ssh/dataplatform.pub') }}"
# Account SSH key name of remote user. Ansible will use this key name to
# provision the managed machines.
ansible_ssh_key: dataplatform

cluster_name: cluster.local

# A list of insecure registrys you might need to define
# NOTE: currently multiply IP/URL/CIDR insecure registrys is NOT supported
insecure_registrys:
  - "platform-registry:5000"

# Enable for use kubeadm for deploy kubernetes 1.9
kubeadm: true

# Turn to false to disable the kube-ui addon for this cluster
kube_ui: true

# Turn to false to disable the kube-dash addon for this cluster
kube_dash: false