---
- name: create folder for dashboard
  file: 
    path: /opt/dashboard
    state: directory
    mode: 640

- name: copy yaml files
  copy:
    src: "files/{{ item }}"
    dest: /opt/dashboard/
  with_items:
    - kubernetes-dashboard.yaml
    - secure-dashboard.yaml

- name: Deploy insecure dashboard
  shell: sudo kubectl create -f /opt/dashboard/kubernetes-dashboard.yaml
  ignore_errors: yes

- name: delay for dashboard
  pause:
    seconds: 15

- name: Delete default admin
  shell: sudo kubectl delete sa kubernetes-dashboard -n kube-system
  ignore_errors: yes

- name: Create Secure admin
  shell: sudo kubectl create -f /opt/dashboard/secure-dashboard.yaml
  ignore_errors: yes

- name:  To see token use - "kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')"
  pause:
    seconds: 1

- name: Show Dashboard creds
  shell: kubectl -n kube-system describe secret $(kubectl -n kube-system get secret | grep admin-user | awk '{print $1}')