---
- hosts:  all
  gather_facts: yes
  tasks:
  - name: upgrade all packages
    become: yes
    yum:
      name: "*"
      state: latest
      skip_broken: yes


  - name: install wget
    become: yes
    yum:
      name: wget
      state: latest