---
- name: Make kubectl running from regular user
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy kubernetes config
  become: yes
  copy:
    src: /etc/kubernetes/admin.conf
    remote_src: yes
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
